export type Guide = { slug: string; title: string; description: string; vertical: string; updatedAt: string; summary: string; steps: string[]; questions: string[]; sources: { label: string; url: string }[] };

export const guides: Guide[] = [
  { slug: "house-cleaning-estimate-checklist", title: "ハウスクリーニングの見積もり前チェックリスト", description: "作業範囲と追加料金の確認を、見積もり前に進めるための実用ガイドです。", vertical: "house-cleaning", updatedAt: "2026-07-24", summary: "同じ条件で比較するには、依頼場所・希望箇所・汚れの状況・希望日時を整理してから、複数社の公式見積もりを確認することが大切です。", steps: ["依頼したい箇所と台数をメモする", "汚れや設置状況が分かる写真を用意する", "作業範囲と追加料金の条件を確認する", "駐車場代・出張費・オプションの有無を確認する", "作業日時とキャンセル条件を確認する", "同じ条件で複数の見積もりを比べる"], questions: ["基本料金に含まれる作業範囲はどこまでですか？", "追加料金が発生する条件はありますか？", "駐車場代や出張費は別途かかりますか？"], sources: [{ label: "ダスキン サービスマスター公式サイト", url: "https://www.duskin.jp/servicemaster/" }, { label: "おそうじ本舗公式サイト", url: "https://www.osoujihonpo.com/" }] },
  { slug: "moving-estimate-checklist", title: "引越し見積もりで確認したい項目", description: "荷物量・日程・オプションを揃え、後から条件が変わらない見積もり比較を進めます。", vertical: "moving", updatedAt: "2026-07-24", summary: "引越し料金は荷物量・時期・移動距離・作業条件で変わります。見積もりごとに前提を揃え、含まれるサービスを確認しましょう。", steps: ["引越し日と時間帯の希望を決める", "荷物量と大型家具をリストにする", "現住所と新居の階数・エレベーター有無を確認する", "梱包・開梱・資材など必要なオプションを整理する", "補償内容とキャンセル条件を確認する", "同条件の見積もりを並べて比較する"], questions: ["見積もりに含まれる作業と含まれない作業は何ですか？", "追加料金が発生するケースはありますか？", "荷物の破損時の補償内容はどうなっていますか？"], sources: [{ label: "アート引越センター公式サイト", url: "https://www.the0123.com/" }, { label: "サカイ引越センター公式サイト", url: "https://www.hikkoshi-sakai.co.jp/index.html" }] },
  { slug: "housekeeping-first-request", title: "初めての家事代行：依頼前の準備", description: "家事代行を初めて頼むときに、希望内容と訪問条件を伝えやすくするガイドです。", vertical: "housekeeping", updatedAt: "2026-07-24", summary: "依頼内容・優先順位・利用頻度・立ち会いの有無を先に整理すると、相談や初回利用をスムーズに進められます。", steps: ["依頼したい家事を優先順位つきで書き出す", "希望する曜日・時間帯・利用頻度を決める", "訪問時の入室方法と立ち会いの有無を確認する", "用意する掃除用具や食材を確認する", "鍵の預かり・補償・キャンセル条件を確認する", "初回後に次回への希望をメモする"], questions: ["依頼できる作業と依頼できない作業は何ですか？", "用意が必要な道具や食材はありますか？", "不在時の利用条件や鍵の扱いはどうなりますか？"], sources: [{ label: "ベアーズ公式サイト", url: "https://www.happy-bears.com/" }, { label: "CaSy公式サイト", url: "https://casy.co.jp/" }] },
];

export function getGuide(slug: string) { return guides.find((guide) => guide.slug === slug); }
