export type Guide = { slug: string; title: string; description: string; vertical: string; updatedAt: string; summary: string; steps: string[]; questions: string[]; sources: { label: string; url: string }[] };

export const guides: Guide[] = [
  { slug: "house-cleaning-estimate-checklist", title: "ハウスクリーニングの見積もり前チェックリスト", description: "作業範囲と追加料金の確認を、見積もり前に進めるための実用ガイドです。", vertical: "house-cleaning", updatedAt: "2026-07-24", summary: "同じ条件で比較するには、依頼場所・希望箇所・汚れの状況・希望日時を整理してから、複数社の公式見積もりを確認することが大切です。", steps: ["依頼したい箇所と台数をメモする", "汚れや設置状況が分かる写真を用意する", "作業範囲と追加料金の条件を確認する", "駐車場代・出張費・オプションの有無を確認する", "作業日時とキャンセル条件を確認する", "同じ条件で複数の見積もりを比べる"], questions: ["基本料金に含まれる作業範囲はどこまでですか？", "追加料金が発生する条件はありますか？", "駐車場代や出張費は別途かかりますか？"], sources: [{ label: "ダスキン サービスマスター公式サイト", url: "https://www.duskin.jp/servicemaster/" }, { label: "おそうじ本舗公式サイト", url: "https://www.osoujihonpo.com/" }] },
  { slug: "moving-estimate-checklist", title: "引越し見積もりで確認したい項目", description: "荷物量・日程・オプションを揃え、後から条件が変わらない見積もり比較を進めます。", vertical: "moving", updatedAt: "2026-07-24", summary: "引越し料金は荷物量・時期・移動距離・作業条件で変わります。見積もりごとに前提を揃え、含まれるサービスを確認しましょう。", steps: ["引越し日と時間帯の希望を決める", "荷物量と大型家具をリストにする", "現住所と新居の階数・エレベーター有無を確認する", "梱包・開梱・資材など必要なオプションを整理する", "補償内容とキャンセル条件を確認する", "同条件の見積もりを並べて比較する"], questions: ["見積もりに含まれる作業と含まれない作業は何ですか？", "追加料金が発生するケースはありますか？", "荷物の破損時の補償内容はどうなっていますか？"], sources: [{ label: "アート引越センター公式サイト", url: "https://www.the0123.com/" }, { label: "サカイ引越センター公式サイト", url: "https://www.hikkoshi-sakai.co.jp/index.html" }] },
  { slug: "housekeeping-first-request", title: "初めての家事代行：依頼前の準備", description: "家事代行を初めて頼むときに、希望内容と訪問条件を伝えやすくするガイドです。", vertical: "housekeeping", updatedAt: "2026-07-24", summary: "依頼内容・優先順位・利用頻度・立ち会いの有無を先に整理すると、相談や初回利用をスムーズに進められます。", steps: ["依頼したい家事を優先順位つきで書き出す", "希望する曜日・時間帯・利用頻度を決める", "訪問時の入室方法と立ち会いの有無を確認する", "用意する掃除用具や食材を確認する", "鍵の預かり・補償・キャンセル条件を確認する", "初回後に次回への希望をメモする"], questions: ["依頼できる作業と依頼できない作業は何ですか？", "用意が必要な道具や食材はありますか？", "不在時の利用条件や鍵の扱いはどうなりますか？"], sources: [{ label: "ベアーズ公式サイト", url: "https://www.happy-bears.com/" }, { label: "CaSy公式サイト", url: "https://casy.co.jp/" }] },
  { slug: "garden-pruning-estimate-checklist", title: "庭木剪定・草刈りの見積もり前チェックリスト", description: "庭の状態や処分条件を揃え、剪定・伐採・草刈りの相談を進めるガイドです。", vertical: "garden-care", updatedAt: "2026-07-24", summary: "樹木の本数・高さ・作業場所・枝葉の処分を整理しておくと、現地見積もりの前提を揃えやすくなります。", steps: ["手入れしたい木や場所を写真に撮る", "本数・おおよその高さ・作業内容を整理する", "隣地や電線など作業上の注意点を確認する", "枝葉・伐採木の処分費を確認する", "定期管理が必要かを検討する", "同じ条件で見積もりを比較する"], questions: ["剪定・伐採・草刈りのどこまでを依頼しますか？", "枝葉や伐採木の処分費は含まれますか？", "現地見積もり後に追加費用が発生する条件はありますか？"], sources: [{ label: "ダスキン トータルグリーン公式サイト", url: "https://totalgreen.duskin.jp/" }, { label: "oh!庭ya!公式サイト", url: "https://www.oh28ya.com/" }] },
  { slug: "pest-control-before-request", title: "害虫・害獣駆除を依頼する前の確認項目", description: "発生場所や被害状況を整理し、駆除と再発防止を比較するためのガイドです。", vertical: "pest-control", updatedAt: "2026-07-24", summary: "対象の種類が不明でも、発見場所・時間帯・被害状況を記録しておくと、適切な相談につながります。", steps: ["虫や害獣を見た場所と日時を記録する", "写真・被害箇所・侵入経路の心当たりを整理する", "家族やペットへの配慮が必要か確認する", "駆除だけでなく予防策も確認する", "保証・再訪・追加料金の条件を確認する", "複数社へ同じ情報で相談する"], questions: ["どの害虫・害獣への対応が可能ですか？", "薬剤の使用方法や安全上の注意は何ですか？", "再発防止や保証の条件はありますか？"], sources: [{ label: "ダスキン ターミニックス公式サイト", url: "https://www.duskin.jp/terminix/" }] },
  { slug: "locksmith-emergency-checklist", title: "鍵開け・鍵交換を頼む前の確認項目", description: "緊急時でも必要な確認を落ち着いて進めるためのガイドです。", vertical: "locksmith", updatedAt: "2026-07-24", summary: "鍵の種類・場所・本人確認書類の有無を伝え、作業前に出張費を含む見積もりを確認しましょう。", steps: ["鍵の場所と状況を確認する", "賃貸の場合は管理会社への連絡要否を確認する", "本人確認書類を準備する", "作業前に出張費を含む総額見積もりを確認する", "交換する鍵の種類と防犯性能を確認する", "作業後の保証や支払い方法を確認する"], questions: ["作業前に総額の見積もりを示してもらえますか？", "本人確認や所有・使用権の確認はどのように行いますか？", "交換後の鍵や部品には保証がありますか？"], sources: [{ label: "カギ110番公式サイト", url: "https://www.kagi110ban.jp/" }] },
  { slug: "plumbing-repair-checklist", title: "水漏れ・つまり修理の依頼前チェックリスト", description: "水を止める初動と、作業料金を確認してから依頼するためのガイドです。", vertical: "plumbing", updatedAt: "2026-07-24", summary: "緊急時は安全を優先し、水漏れの場所・症状・止水栓の状況を伝えたうえで、作業前の見積もりを確認しましょう。", steps: ["漏水箇所と症状を写真や動画で記録する", "止水栓・元栓の位置を確認する", "賃貸の場合は管理会社へ連絡する", "出張費・基本料金・部品代を分けて確認する", "作業前の見積もりに同意してから依頼する", "作業内容と保証を記録する"], questions: ["出張費・基本料金・部品代はそれぞれいくらですか？", "水道局指定工事店か、必要な資格・届出は確認できますか？", "作業後の保証や再訪条件はありますか？"], sources: [{ label: "クラシアン公式サイト", url: "https://www.qracian.co.jp/" }, { label: "イースマイル公式サイト", url: "https://www.esmile-24.com/" }] },
  { slug: "electrical-work-checklist", title: "電気工事・エアコン設置前の確認項目", description: "設置場所と追加工事の条件を整理し、安全に工事を依頼するためのガイドです。", vertical: "electrical", updatedAt: "2026-07-24", summary: "工事の可否や追加費用は設置環境で変わります。機器の型番・設置場所・既存配線を確認し、施工条件を揃えて相談しましょう。", steps: ["機器の型番と設置希望場所を確認する", "コンセント・専用回路・分電盤の状況を確認する", "室外機やアンテナなど屋外作業の場所を確認する", "追加工事の条件と料金を確認する", "施工者の資格・保証・工事範囲を確認する", "工事後の動作確認と書類を保管する"], questions: ["標準工事に含まれる内容は何ですか？", "追加工事が必要になる条件と料金は何ですか？", "電気工事士が施工する範囲と保証はどうなっていますか？"], sources: [{ label: "エディオン工事サービス公式サイト", url: "https://service-info.edion.jp/service/construction/" }, { label: "ヤマダウェブコム公式サイト", url: "https://www.yamada-denkiweb.com/info/wcontents/kouji_aircon.html" }] },
];

export function getGuide(slug: string) { return guides.find((guide) => guide.slug === slug); }
