export type Provider = { id: string; vertical: string; name: string; coverage: string; services: string[]; highlights: string[]; pricing: string; sourceUrl: string; sourceLabel: string; verifiedAt: string };

// Official-site facts, checked 2026-07-24. Availability and final pricing must be confirmed with each provider.
export const providers: Provider[] = [
  { id: "duskin-service-master", vertical: "house-cleaning", name: "ダスキン サービスマスター", coverage: "公式サイトに全国店舗一覧・地域別料金案内あり", services: ["エアコン", "水まわり", "窓まわり", "セットプラン"], highlights: ["WEBお見積りに対応", "1回・定期利用を選択可能", "47都道府県に店舗"], pricing: "地域別料金は公式サイトで確認", sourceUrl: "https://www.duskin.jp/servicemaster/", sourceLabel: "ダスキン公式サイト", verifiedAt: "2026-07-24" },
  { id: "osouji-honpo", vertical: "house-cleaning", name: "おそうじ本舗", coverage: "対応店舗・対応エリアは公式サイトで確認", services: ["エアコン", "水まわり", "洗濯機", "キッチン・換気扇"], highlights: ["お引越し前後の丸ごと清掃", "在宅丸ごとクリーニング", "無料お見積りの案内あり"], pricing: "料金・オプションは公式サイトで確認", sourceUrl: "https://www.osoujihonpo.com/", sourceLabel: "おそうじ本舗公式サイト", verifiedAt: "2026-07-24" },
  { id: "bears-house-cleaning", vertical: "house-cleaning", name: "ベアーズ ハウスクリーニング", coverage: "対応エリアは公式サイトで確認", services: ["エアコン", "キッチン", "換気扇", "浴室・トイレ"], highlights: ["スポットプラン", "定期プラン", "予約申込みの案内あり"], pricing: "プラン・料金は公式サイトで確認", sourceUrl: "https://www.happy-bears.com/houseclean/", sourceLabel: "ベアーズ公式サイト", verifiedAt: "2026-07-24" },
  { id: "art-moving", vertical: "moving", name: "アート引越センター", coverage: "地域の担当店・予約状況は公式見積もりで確認", services: ["単身引越し", "家族引越し", "オフィス・事務所移転", "電気工事などのオプション"], highlights: ["学割・レディース・シニア向けパック", "電話・メール見積もりの案内あり", "見積もり時期の案内あり"], pricing: "無料見積もり。料金は条件により変動", sourceUrl: "https://www.the0123.com/", sourceLabel: "アート引越センター公式サイト", verifiedAt: "2026-07-24" },
  { id: "sakai-moving", vertical: "moving", name: "サカイ引越センター", coverage: "公式サイトで全国の対応エリア検索を提供", services: ["単身引越し", "家族引越し", "オフィス移転", "オンライン見積り（単身）"], highlights: ["フル・スタンダード・エコノミーのプラン", "訪問・電話見積もり", "単身向けWeb完結サービスの案内あり"], pricing: "無料見積もり。料金は条件により変動", sourceUrl: "https://www.hikkoshi-sakai.co.jp/index.html", sourceLabel: "サカイ引越センター公式サイト", verifiedAt: "2026-07-24" },
  { id: "bears-housekeeping", vertical: "housekeeping", name: "ベアーズ 家事代行", coverage: "対応エリアは公式サイトで確認", services: ["掃除", "料理", "買い物", "定期利用"], highlights: ["初回お試しプランの案内", "定期プランの案内", "利用エリアを公式サイトで確認可能"], pricing: "プラン・料金は公式サイトで確認", sourceUrl: "https://www.happy-bears.com/", sourceLabel: "ベアーズ公式サイト", verifiedAt: "2026-07-24" },
  { id: "casy-housekeeping", vertical: "housekeeping", name: "CaSy", coverage: "対応エリアは公式サイトで確認", services: ["掃除代行", "料理代行", "整理収納", "買い物オプション"], highlights: ["24時間365日予約・変更・キャンセルの案内", "損害保険加入の案内", "掃除・料理の詳細料金を公開"], pricing: "掃除・料理代行は1時間2,790円（税込）〜。交通費等は別途", sourceUrl: "https://casy.co.jp/", sourceLabel: "CaSy公式サイト", verifiedAt: "2026-07-24" },
  { id: "duskin-totalgreen", vertical: "garden-care", name: "ダスキン トータルグリーン", coverage: "対応エリアは公式サイトで確認", services: ["庭木の剪定", "雑草対策", "病害虫防除", "芝生の手入れ"], highlights: ["部分的な庭の手入れに対応", "定期メンテナンスの案内", "庭木・雑草・芝生をまとめて相談可能"], pricing: "料金・対応内容は公式サイトで確認", sourceUrl: "https://totalgreen.duskin.jp/", sourceLabel: "ダスキン トータルグリーン公式サイト", verifiedAt: "2026-07-24" },
  { id: "oh28ya", vertical: "garden-care", name: "oh!庭ya!", coverage: "東京都・埼玉県・神奈川県・大阪府など、対応エリアは公式サイトで確認", services: ["庭木剪定", "伐採", "草刈り・芝刈り", "草取り・防草対策"], highlights: ["作業前に見積もりを提示", "庭木・生垣の刈込み", "空き地・空き家管理の案内"], pricing: "剪定は1本500円〜など。条件により変動", sourceUrl: "https://www.oh28ya.com/", sourceLabel: "oh!庭ya!公式サイト", verifiedAt: "2026-07-24" },
  { id: "duskin-terminix", vertical: "pest-control", name: "ダスキン ターミニックス", coverage: "対応エリアは公式サイトで確認", services: ["ゴキブリ駆除", "シロアリ対策", "ハチ駆除", "ネズミ対策"], highlights: ["予防管理を重視したIPMの考え方", "薬剤使用を抑えた方法を案内", "害虫・害獣の駆除と予防を相談可能"], pricing: "料金・対応内容は公式サイトで確認", sourceUrl: "https://www.duskin.jp/terminix/", sourceLabel: "ダスキン ターミニックス公式サイト", verifiedAt: "2026-07-24" },
  { id: "kagi110ban", vertical: "locksmith", name: "カギ110番", coverage: "日本全国。対応地域は公式サイトで確認", services: ["鍵開け", "鍵修理", "合鍵作成", "鍵交換・取付"], highlights: ["24時間365日対応の案内", "住宅・車・金庫などの鍵トラブル", "防犯対策の相談を案内"], pricing: "作業料金・交通費等は公式サイトで確認", sourceUrl: "https://www.kagi110ban.jp/", sourceLabel: "カギ110番公式サイト", verifiedAt: "2026-07-24" },
  { id: "qracian", vertical: "plumbing", name: "クラシアン", coverage: "対応エリアは公式サイトで確認", services: ["トイレのつまり・水漏れ", "キッチンの水漏れ・交換", "浴室・洗面所の水トラブル", "蛇口・給湯器の修理"], highlights: ["24時間365日受付の案内", "水まわりの修理・交換", "施工別の作業料金例を公開"], pricing: "作業料金は8,800円（税込）＋事務手数料〜。条件により変動", sourceUrl: "https://www.qracian.co.jp/", sourceLabel: "クラシアン公式サイト", verifiedAt: "2026-07-24" },
  { id: "esmile", vertical: "plumbing", name: "イースマイル", coverage: "対応エリアは公式サイトで確認", services: ["トイレのつまり・水漏れ", "蛇口・排水管の修理", "キッチン・浴室の水トラブル", "水道設備の修理・交換"], highlights: ["水トラブル・水道設備の修理交換", "料金・対応内容を公式サイトで案内", "地域の対応可否を確認可能"], pricing: "料金・追加費用は公式サイトで確認", sourceUrl: "https://www.esmile-24.com/", sourceLabel: "イースマイル公式サイト", verifiedAt: "2026-07-24" },
  { id: "edion-construction", vertical: "electrical", name: "エディオン 工事サービス", coverage: "対応地域・工事可否は公式サイトまたは店舗で確認", services: ["エアコン取付工事", "アンテナ工事", "電気工事", "照明工事"], highlights: ["手持ちエアコンの取付工事を案内", "電気工事士による施工の案内", "大型家電の訪問修理も案内"], pricing: "工事料金・追加工事は公式サイトで確認", sourceUrl: "https://service-info.edion.jp/service/construction/", sourceLabel: "エディオン工事サービス公式サイト", verifiedAt: "2026-07-24" },
  { id: "yamada-construction", vertical: "electrical", name: "ヤマダデンキ 工事サービス", coverage: "対応地域・工事可否は公式サイトまたは店舗で確認", services: ["エアコン設置", "アンテナ工事", "電気工事", "家電の配送設置"], highlights: ["エアコン工事メニューを公開", "設置状況により追加工事を案内", "全国配送設置の案内"], pricing: "設置場所・追加工事により料金が変動", sourceUrl: "https://www.yamada-denkiweb.com/info/wcontents/kouji_aircon.html", sourceLabel: "ヤマダウェブコム公式サイト", verifiedAt: "2026-07-24" },
];

export function getProviders(vertical: string) { return providers.filter((provider) => provider.vertical === vertical); }
export function getProvider(id: string) { return providers.find((provider) => provider.id === id); }
