export type Provider = { id: string; vertical: string; name: string; coverage: string; services: string[]; highlights: string[]; pricing: string; sourceUrl: string; sourceLabel: string; verifiedAt: string };

// Official-site facts, checked 2026-07-24. Availability and final pricing must be confirmed with each provider.
export const providers: Provider[] = [
  { id: "duskin-service-master", vertical: "house-cleaning", name: "ダスキン サービスマスター", coverage: "公式サイトに全国店舗一覧・地域別料金案内あり", services: ["エアコン", "水まわり", "窓まわり", "セットプラン"], highlights: ["WEBお見積りに対応", "1回・定期利用を選択可能", "47都道府県に店舗"], pricing: "地域別料金は公式サイトで確認", sourceUrl: "https://www.duskin.jp/servicemaster/", sourceLabel: "ダスキン公式サイト", verifiedAt: "2026-07-24" },
  { id: "osouji-honpo", vertical: "house-cleaning", name: "おそうじ本舗", coverage: "対応店舗・対応エリアは公式サイトで確認", services: ["エアコン", "水まわり", "洗濯機", "キッチン・換気扇"], highlights: ["お引越し前後の丸ごと清掃", "在宅丸ごとクリーニング", "無料お見積りの案内あり"], pricing: "料金・オプションは公式サイトで確認", sourceUrl: "https://www.osoujihonpo.com/", sourceLabel: "おそうじ本舗公式サイト", verifiedAt: "2026-07-24" },
  { id: "bears-house-cleaning", vertical: "house-cleaning", name: "ベアーズ ハウスクリーニング", coverage: "対応エリアは公式サイトで確認", services: ["エアコン", "キッチン", "換気扇", "浴室・トイレ"], highlights: ["スポットプラン", "定期プラン", "予約申込みの案内あり"], pricing: "プラン・料金は公式サイトで確認", sourceUrl: "https://www.happy-bears.com/houseclean/", sourceLabel: "ベアーズ公式サイト", verifiedAt: "2026-07-24" },
  { id: "art-moving", vertical: "moving", name: "アート引越センター", coverage: "地域の担当店・予約状況は公式見積もりで確認", services: ["単身引越し", "家族引越し", "オフィス・事務所移転", "電気工事などのオプション"], highlights: ["学割・レディース・シニア向けパック", "電話・メール見積もりの案内あり", "見積もり時期の案内あり"], pricing: "無料見積もり。料金は条件により変動", sourceUrl: "https://www.the0123.com/", sourceLabel: "アート引越センター公式サイト", verifiedAt: "2026-07-24" },
  { id: "sakai-moving", vertical: "moving", name: "サカイ引越センター", coverage: "公式サイトで全国の対応エリア検索を提供", services: ["単身引越し", "家族引越し", "オフィス移転", "オンライン見積り（単身）"], highlights: ["フル・スタンダード・エコノミーのプラン", "訪問・電話見積もり", "単身向けWeb完結サービスの案内あり"], pricing: "無料見積もり。料金は条件により変動", sourceUrl: "https://www.hikkoshi-sakai.co.jp/index.html", sourceLabel: "サカイ引越センター公式サイト", verifiedAt: "2026-07-24" },
  { id: "bears-housekeeping", vertical: "housekeeping", name: "ベアーズ 家事代行", coverage: "対応エリアは公式サイトで確認", services: ["掃除", "料理", "買い物", "定期利用"], highlights: ["初回お試しプランの案内", "定期プランの案内", "利用エリアを公式サイトで確認可能"], pricing: "プラン・料金は公式サイトで確認", sourceUrl: "https://www.happy-bears.com/", sourceLabel: "ベアーズ公式サイト", verifiedAt: "2026-07-24" },
  { id: "casy-housekeeping", vertical: "housekeeping", name: "CaSy", coverage: "対応エリアは公式サイトで確認", services: ["掃除代行", "料理代行", "整理収納", "買い物オプション"], highlights: ["24時間365日予約・変更・キャンセルの案内", "損害保険加入の案内", "掃除・料理の詳細料金を公開"], pricing: "掃除・料理代行は1時間2,790円（税込）〜。交通費等は別途", sourceUrl: "https://casy.co.jp/", sourceLabel: "CaSy公式サイト", verifiedAt: "2026-07-24" },
];

export function getProviders(vertical: string) { return providers.filter((provider) => provider.vertical === vertical); }
