"use client";

import Link from "next/link";
import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { cities } from "../../lib/cities";
import { guides } from "../../lib/guides";
import { relatedServices } from "../../lib/related-services";
import { getProviders, type Provider } from "../../lib/providers";
import type { Vertical } from "../../lib/verticals";

type Review = { id: number; nickname: string; rating: number; body: string; helpful: number; serviceType: string; usageMonth: string; prefecture: string; estimateMatch: string; goodPoint: string; cautionPoint: string; wouldUseAgain: boolean; verificationStatus: "verified" | "unverified" };
type Campaign = { id: number; name: string; asp: string };
const prefectures = ["東京都", "大阪府", "神奈川県", "埼玉県"];
const estimateLabels: Record<string, string> = { "as-expected": "見積もりどおり", higher: "見積もりより高かった", lower: "見積もりより安かった", unknown: "比較できない" };

export default function VerticalPage({ vertical, initialCity }: { vertical: Vertical; initialCity?: string }) {
  const [city, setCity] = useState(initialCity || cities[0].name);
  const [service, setService] = useState(vertical.services[0]);
  const providers = useMemo(() => getProviders(vertical.slug), [vertical.slug]);
  const [selected, setSelected] = useState<Provider | undefined>(() => providers[0]);
  const [email, setEmail] = useState(""); const [consent, setConsent] = useState(false); const [leadStatus, setLeadStatus] = useState(""); const [ctaVariant] = useState<"official-first" | "consult-first">(() => { if (typeof window === "undefined") return "official-first"; const key = "machiselect-cta-order-v1"; const stored = window.localStorage.getItem(key); if (stored === "official-first" || stored === "consult-first") return stored; const value = Math.random() < 0.5 ? "official-first" : "consult-first"; window.localStorage.setItem(key, value); return value; });
  const [reviews, setReviews] = useState<Review[]>([]); const [nickname, setNickname] = useState(""); const [rating, setRating] = useState(5); const [body, setBody] = useState(""); const [usageMonth, setUsageMonth] = useState(""); const [prefecture, setPrefecture] = useState("東京都"); const [estimateMatch, setEstimateMatch] = useState("unknown"); const [goodPoint, setGoodPoint] = useState(""); const [cautionPoint, setCautionPoint] = useState(""); const [wouldUseAgain, setWouldUseAgain] = useState(false); const [reviewStatus, setReviewStatus] = useState(""); const [campaigns, setCampaigns] = useState<Campaign[]>([]);
  const track = useCallback((event: "view" | "compare" | "cta", providerId?: string) => void fetch("/api/events", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ vertical: vertical.slug, city, providerId, event }), keepalive: true }), [city, vertical.slug]);
  const loadReviews = useCallback(() => void fetch(`/api/reviews?vertical=${vertical.slug}&city=${encodeURIComponent(city)}`).then((r) => r.json()).then((data) => setReviews(data.reviews || [])).catch(() => setReviews([])), [city, vertical.slug]);
  useEffect(() => { track("view"); loadReviews(); }, [loadReviews, track]);
  useEffect(() => { void fetch(`/api/campaigns?vertical=${vertical.slug}`).then((r) => r.json()).then((data) => setCampaigns(data.campaigns || [])).catch(() => setCampaigns([])); }, [vertical.slug]);
  async function submitLead(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!selected) return; track("cta", `${selected.id}:consult:${ctaVariant}`); const response = await fetch("/api/leads", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ vertical: vertical.slug, providerId: selected.id, city, service, home: "web-comparison", email, consent }) }); setLeadStatus(response.ok ? "相談依頼を受け付けました。" : "送信できませんでした。もう一度お試しください。"); if (response.ok) setEmail(""); }
  async function submitReview(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const response = await fetch("/api/reviews", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ vertical: vertical.slug, providerId: selected?.id || "", city, nickname, rating, body, prefecture, serviceType: service, usageMonth, estimateMatch, goodPoint, cautionPoint, wouldUseAgain }) }); const data = await response.json() as { error?: string; message?: string }; setReviewStatus(response.ok ? data.message || "投稿を受け付けました。" : data.error || "送信できませんでした。"); if (response.ok) { setNickname(""); setBody(""); setUsageMonth(""); setGoodPoint(""); setCautionPoint(""); setWouldUseAgain(false); } }
  async function markHelpful(id: number) { const response = await fetch(`/api/reviews/${id}/helpful`, { method: "POST" }); if (response.ok) { const data = await response.json() as { helpful: number }; setReviews((items) => items.map((item) => item.id === id ? { ...item, helpful: data.helpful } : item)); } }
  async function reportReview(id: number) { const reason = window.prompt("通報理由を選んで入力してください: personal-info / abuse / not-experience / other"); if (!reason) return; const response = await fetch(`/api/reviews/${id}/report`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ reason }) }); setReviewStatus(response.ok ? "通報を受け付けました。公開せずに確認します。" : "通報を受け付けられませんでした。"); }
  const faqs = [{ question: `${vertical.name}の料金はどのように比べればよいですか？`, answer: "基本料金だけでなく作業範囲、追加料金、対応条件を見積もり前に確認してください。" }, { question: "口コミはすぐ公開されますか？", answer: "投稿は確認後に公開します。個人情報や利用確認ができない内容は公開しません。" }];
  const guide = guides.find((item) => item.vertical === vertical.slug);
  const related = relatedServices[vertical.slug] || [];
  return <main style={{ "--green": vertical.accent } as React.CSSProperties}>
    <header><Link href="/" className="logo">まち<span>セレクト</span></Link><nav><a href="#results">比較</a><a href="#reviews">口コミ</a><a href="#request">相談</a></nav></header>
    <section className="hero"><p>{vertical.category.toUpperCase()} · LOCAL COMPARISON</p><h1>{city}の<br /><em>{vertical.name}を比較</em></h1><span>公式サイトで確認できるサービス情報と、利用条件が近い人の口コミを分けて掲載しています。</span><a href="#results" onClick={() => track("compare")}>比較表を見る →</a></section>
    <section className="search" aria-label="比較条件"><label>地域<select value={city} onChange={(e) => setCity(e.target.value)}>{cities.map((item) => <option key={item.slug}>{item.name}</option>)}</select></label><label>サービス<select value={service} onChange={(e) => setService(e.target.value)}>{vertical.services.map((item) => <option key={item}>{item}</option>)}</select></label><a href="#results" onClick={() => track("compare")}>条件を確認</a></section>
    {guide && <section className="guide-callout"><p className="eyebrow">BEFORE YOU COMPARE</p><h2>{guide.title}</h2><p>{guide.description}</p><Link href={`/guides/${guide.slug}`}>選び方・注意点を読む →</Link></section>}
    <section className="results" id="results"><div className="head"><div><p>OFFICIAL LISTINGS</p><h2>{city}の{vertical.name}</h2></div><span>{providers.length}社の公式情報</span></div><div className="cards">{providers.map((provider) => <article key={provider.id} className={selected?.id === provider.id ? "selected-provider" : ""}><div><b>{provider.name}</b><strong>公式情報</strong></div><small>{provider.coverage}</small><p className="pricing-note">{provider.pricing}</p><h3>対応サービス</h3><ul>{provider.services.map((item) => <li key={item}>{item}</li>)}</ul><dl>{provider.highlights.map((item, index) => <div key={item}><dt>{vertical.points[index]}</dt><dd>{item}</dd></div>)}</dl><Link className="official-link" href={`/providers/${provider.id}`}>掲載詳細・出典を見る →</Link>{ctaVariant === "official-first" ? <><a className="official-link" href={provider.sourceUrl} target="_blank" rel="noreferrer" onClick={() => track("cta", `${provider.id}:official:${ctaVariant}`)}>公式サイトで確認 →</a><button onClick={() => { setSelected(provider); document.getElementById("request")?.scrollIntoView({ behavior: "smooth" }); }}>比較相談をする</button></> : <><button onClick={() => { setSelected(provider); document.getElementById("request")?.scrollIntoView({ behavior: "smooth" }); }}>比較相談をする</button><a className="official-link" href={provider.sourceUrl} target="_blank" rel="noreferrer" onClick={() => track("cta", `${provider.id}:official:${ctaVariant}`)}>公式サイトで確認 →</a></>}<small className="source-note">出典: {provider.sourceLabel} · 確認日 {provider.verifiedAt}</small></article>)}</div></section>
    <section className="compare">{vertical.points.map((point, index) => <div key={point}><b>0{index + 1}</b><h3>{point}を確認</h3><p>公式サイトと見積もりで、依頼前に条件を確認しましょう。</p></div>)}</section>
    {campaigns.length > 0 && <section className="sponsored-section"><p className="eyebrow">SPONSORED</p><h2>広告・提携の比較枠</h2><p>広告であることを明示し、通常の公式情報による比較とは分けて表示しています。</p><div>{campaigns.map((campaign) => <a key={campaign.id} href={`/go/${campaign.id}?city=${encodeURIComponent(city)}`} onClick={() => track("cta", `campaign:${campaign.id}`)}><small>スポンサー · {campaign.asp}</small><b>{campaign.name}</b><span>詳細を確認 →</span></a>)}</div></section>}
    <section className="faq-section"><p className="eyebrow">HELPFUL ANSWERS</p><h2>よくある質問</h2>{faqs.map((faq) => <details key={faq.question}><summary>{faq.question}</summary><p>{faq.answer}</p></details>)}</section>
    <section className="review-section" id="reviews"><div><p className="eyebrow">LOCAL REVIEWS</p><h2>{city}の口コミ</h2><p className="review-note">編集部評価とは分けて表示します。投稿は利用時期・地域・見積もりとの差を確認後に公開します。</p>{reviews.length ? reviews.map((review) => <article className="review" key={review.id}><b>{"★".repeat(review.rating)} <span>{review.nickname}</span></b><small>{review.verificationStatus === "verified" ? "利用確認済み" : "利用未確認"} · {review.prefecture} · {review.serviceType} · {review.usageMonth} · {estimateLabels[review.estimateMatch]}</small><p>{review.body}</p>{review.goodPoint && <p><strong>良かった点:</strong> {review.goodPoint}</p>}{review.cautionPoint && <p><strong>注意点:</strong> {review.cautionPoint}</p>}<small>{review.wouldUseAgain ? "再利用したい" : "再利用は未定"}</small><div><button type="button" onClick={() => markHelpful(review.id)}>参考になった {review.helpful}</button><button type="button" onClick={() => reportReview(review.id)}>通報</button></div></article>) : <p className="empty">まだ確認済みの口コミはありません。利用後の率直な体験をお待ちしています。</p>}</div><form onSubmit={submitReview}><h3>利用体験を投稿</h3><p className="review-note">高評価のみを求めません。個人情報・住所・伝票番号は書かないでください。</p><label>ニックネーム<input required value={nickname} onChange={(e) => setNickname(e.target.value)} /></label><label>利用した都道府県<select value={prefecture} onChange={(e) => setPrefecture(e.target.value)}>{prefectures.map((item) => <option key={item}>{item}</option>)}</select></label><label>利用月<input required type="month" value={usageMonth} onChange={(e) => setUsageMonth(e.target.value)} /></label><label>満足度<select value={rating} onChange={(e) => setRating(Number(e.target.value))}>{[5, 4, 3, 2, 1].map((item) => <option key={item} value={item}>{item}点</option>)}</select></label><label>見積もりとの差<select value={estimateMatch} onChange={(e) => setEstimateMatch(e.target.value)}>{Object.entries(estimateLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><label>口コミ（10〜500字）<textarea required minLength={10} maxLength={500} value={body} onChange={(e) => setBody(e.target.value)} /></label><label>良かった点（任意）<textarea maxLength={300} value={goodPoint} onChange={(e) => setGoodPoint(e.target.value)} /></label><label>注意点（任意）<textarea maxLength={300} value={cautionPoint} onChange={(e) => setCautionPoint(e.target.value)} /></label><label className="review-again"><input type="checkbox" checked={wouldUseAgain} onChange={(e) => setWouldUseAgain(e.target.checked)} /> また利用したい</label><button>確認用に投稿する</button><output>{reviewStatus}</output></form></section>
    <section className="request" id="request"><div><p>FREE CONSULTATION</p><h2>比較・相談を依頼する</h2><span>{selected ? <><b>{selected.name}</b>について、{city}・{service}の相談を受け付けます。</> : "比較する会社を選択してください。"}</span></div><form onSubmit={submitLead}><label>連絡用メールアドレス<input required type="email" value={email} onChange={(e) => setEmail(e.target.value)} placeholder="you@example.com" /></label><p>{city} · {service}</p><label className="consent"><input required type="checkbox" checked={consent} onChange={(e) => setConsent(e.target.checked)} /> プライバシーポリシーに同意する</label><button disabled={!consent || !selected}>相談を送信</button><output>{leadStatus}</output></form></section>
    <section className="guide-callout"><p className="eyebrow">RELATED SERVICES</p><h2>住まいの関連サービスも確認</h2><p>依頼内容に近いジャンルを、目的別に確認できます。</p><div>{related.map((item) => <Link key={item.slug} href={`/compare/${item.slug}`}><b>{item.label}</b><span>{item.reason}</span></Link>)}</div></section>
    <footer><Link className="logo" href="/">まち<span>セレクト</span></Link><p>{city}の{vertical.name}を、公式情報から比較。</p><small><Link href="/editorial-policy">掲載基準</Link> · <Link href="/disclosure">広告掲載基準</Link></small></footer>
  </main>;
}
