"use client";
import { FormEvent, useMemo, useState } from "react";
const providers=[
{id:"clean-a",name:"まちピカ清掃",area:["新宿区","渋谷区","中野区"],price:12800,rating:4.7,reviews:126,tags:["損害保険","再施工保証","女性スタッフ"],extra:"駐車場なし：実費",slot:"最短 明日"},
{id:"clean-b",name:"暮らしクリーン",area:["新宿区","渋谷区"],price:9900,rating:4.5,reviews:84,tags:["損害保険","土日対応"],extra:"汚れ追加：事前見積",slot:"最短 3日後"},
{id:"clean-c",name:"ホームリセット",area:["中野区","杉並区","新宿区"],price:15400,rating:4.8,reviews:203,tags:["再施工保証","女性スタッフ","写真報告"],extra:"追加料金なし",slot:"最短 2日後"}];
export default function Home(){const[city,setCity]=useState("新宿区"),[place,setPlace]=useState("エアコン"),[home,setHome]=useState("マンション"),[selected,setSelected]=useState(providers[0]),[email,setEmail]=useState(""),[consent,setConsent]=useState(false),[status,setStatus]=useState("");const shown=useMemo(()=>providers.filter(p=>p.area.includes(city)),[city]);
async function send(e:FormEvent){e.preventDefault();try{const r=await fetch("/api/leads",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({providerId:selected.id,city,service:place,home,email,consent})});const body=await r.json() as{error?:string};if(!r.ok)throw new Error(body.error||"登録できませんでした");setStatus(`${selected.name}の見積もり・空き通知を受け付けました`);setEmail("")}catch(error){setStatus(error instanceof Error?error.message:"登録できませんでした")}}
return <main><header><a href="#top" className="logo">まち<span>クリン</span></a><nav><a href="#search">業者を探す</a><a href="#compare">比較基準</a><a href="#request">見積もり</a></nav></header>
<section className="hero" id="top"><p>LOCAL CLEANING COMPARISON</p><h1>近くの清掃業者を、<br/><em>条件まで比べる。</em></h1><span>市町村、住まい、清掃箇所から、料金だけでなく追加費用・保証・空き状況を比較します。</span><a href="#search">市町村から探す →</a><small>掲載内容は初期検証用の架空データです。</small></section>
<section className="search" id="search"><label>市町村<select value={city} onChange={e=>setCity(e.target.value)}>{["新宿区","渋谷区","中野区","杉並区"].map(x=><option key={x}>{x}</option>)}</select></label><label>住居<select value={home} onChange={e=>setHome(e.target.value)}><option>マンション</option><option>戸建て</option><option>店舗</option></select></label><label>清掃箇所<select value={place} onChange={e=>setPlace(e.target.value)}><option>エアコン</option><option>浴室</option><option>キッチン</option><option>水回りセット</option><option>空室全体</option></select></label><a href="#results">比較する →</a></section>
<section className="results" id="results"><div className="head"><div><p>LOCAL RESULTS</p><h2>{city}のハウスクリーニング</h2></div><span>{shown.length}社・{place}の参考比較</span></div><div className="cards">{shown.map((p,i)=><article key={p.id}>{i===0&&<i>条件一致度 No.1</i>}<div><b>{p.name}</b><strong>★ {p.rating}</strong></div><small>口コミ {p.reviews}件</small><h3>¥{p.price.toLocaleString()}〜</h3><p>{place}・{home}の参考価格</p><ul>{p.tags.map(x=><li key={x}>✓ {x}</li>)}</ul><dl><div><dt>追加条件</dt><dd>{p.extra}</dd></div><div><dt>空き目安</dt><dd>{p.slot}</dd></div></dl><button onClick={()=>{setSelected(p);document.getElementById("request")?.scrollIntoView({behavior:"smooth"})}}>見積もり・空き通知 →</button></article>)}</div></section>
<section className="compare" id="compare"><div><b>01</b><h3>総額で比較</h3><p>駐車料金、汚れ、オプションなど追加条件を分けて表示。</p></div><div><b>02</b><h3>安心で比較</h3><p>損害保険、再施工、本人確認、キャンセル条件を確認。</p></div><div><b>03</b><h3>地域別口コミ</h3><p>市町村・清掃箇所・住居タイプごとに口コミを集計。</p></div></section>
<section className="request" id="request"><div><p>FREE ESTIMATE</p><h2>見積もりと空きを確認。</h2><span>選択中：<b>{selected.name}</b><br/>提携先への送客には広告報酬が発生する場合があります。</span></div><form onSubmit={send}><label>通知先メール<input required type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@example.com"/></label><p>{city}・{home}・{place}</p><label className="consent"><input required type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/> 見積もり連絡とプライバシーポリシーに同意</label><button disabled={!consent}>無料で確認する →</button><output>{status}</output></form></section>
<footer><a className="logo" href="#top">まち<span>クリン</span></a><p>地域の生活サービスを、条件まで透明に。</p><small>© 2026 Local Service Finder · 架空データによる初期版</small></footer></main>}
